#!/bin/bash

if g++ statement.cpp -std=c++1z -o statement
then
./statement
rm statement
else
echo "An error while compilation statement.cpp occured"
exit 1
fi

dis=$(glpsol statement.mps --max --presol -o out.presol)
rm -f protocol.presol
echo $dis >> protocol.presol

dis=$(glpsol statement.mps --max --nopresol -o out.nopresol)
rm -f protocol.nopresol
echo $dis >> protocol.nopresol

if g++ parser.cpp -std=c++1z -o parser
then
./parser
rm parser
else
echo "An error while compilation parser.cpp occured"
exit 1
fi

dot -Tjpeg -Gdpi=300 -O flows.dot